include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
  errors:
    # We rely on runtime null-safe fromJson maps; keep these as warnings.
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    use_key_in_widget_constructors: true
